# Generated by Django 2.2 on 2021-05-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotpo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to='static/profile_picture'),
        ),
    ]
