# Generated by Django 2.2 on 2021-05-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotpo', '0002_auto_20210507_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='art_image',
            field=models.ImageField(upload_to='aotpo/static/artwork'),
        ),
    ]
