# Generated by Django 2.2 on 2021-05-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotpo', '0004_auto_20210507_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='art_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
